language: php

php:
  - 5.6

before_install:
  - mysql -e 'CREATE DATABASE homestead;'
  
before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction

script:
  # - php artisan key:generate
  # - php artisan migrate
  # - phpunit
